
name: swlabels
description: SWLabels is a tool for conveniently printing text on SpriteWidget objects
version: 0.1.1
homepage: https://www.blogger.com/blog/posts/4498221098999236379
repository: https://github.com/iLnaar/swlabels
issue_tracker: https://github.com/iLnaar/swlabels/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spritewidget: ^0.9.24
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
